namespace Hurricane.XTest.Core.Const.Enums
{
    public enum QuestionType
    {
        Deffoult,
        Ellieas,
        Varshamova,
        Abramson, 
        BCH,
        Berger, 
        Channel,
        DDC,
        EasyReturn, 
        Entrophy,
        Faira,
        Gray,
        Haphmana,
        Iterative,
        ModulationCheck,
        PrimaryNonDualOnes,
        Recyrent,
        RidaMallera,
        ShenonPhano,
        SystematicHemming,
        CycleHemming,
        ModuleCodeQ,
        Satellite
    }
}
